import os

from dotenv import load_dotenv
from google import genai
from google.genai import types

from .tools import TOOLS

load_dotenv()


# Create the Gemini client.
client = genai.Client(
    api_key=os.getenv("GEMINI_API_KEY")
)


# ---------------------------------------------------------
# TOOL DEFINITIONS
# ---------------------------------------------------------
#
# These definitions tell Gemini which tools are available
# and what parameters each tool requires.
#
# Important:
# This does NOT execute the Python functions.
# It only describes the available capabilities to Gemini.
# ---------------------------------------------------------

tool = types.Tool(
    function_declarations=[

        # Tool 1: Get employee leave balance
        types.FunctionDeclaration(
            name="get_leave_balance",
            description="Get the current leave balance of a specific employee.",

            parameters=types.Schema(
                type=types.Type.OBJECT,
                properties={
                    "employee_id": types.Schema(
                        type=types.Type.STRING,
                        description="The ID of the employee."
                    )
                },
                required=["employee_id"]
            )
        ),

        # Tool 2: Get employee WFH usage
        types.FunctionDeclaration(
            name="get_wfh_days",
            description="Get the number of work-from-home days used by a specific employee this week.",

            parameters=types.Schema(
                type=types.Type.OBJECT,
                properties={
                    "employee_id": types.Schema(
                        type=types.Type.STRING,
                        description="The ID of the employee."
                    )
                },
                required=["employee_id"]
            )
        )
    ]
)


# Test the second tool.
# user_question = "How many WFH days has employee 102 used this week?"
# Gemini must decide which available tool is appropriate.
# user_question = "How many leaves does employee 102 have?"
user_question = (
    "Tell me the leave balance and WFH days for employee 102."
)


# ---------------------------------------------------------
# STEP 1:
# Ask Gemini whether it needs to use a tool.
# ---------------------------------------------------------

response = client.models.generate_content(
    model="gemini-3.5-flash-lite",
    contents=user_question,
    config=types.GenerateContentConfig(
        tools=[tool]
    )
)


# ---------------------------------------------------------
# Handle all tool calls generated by Gemini.
#
# A single user question can require multiple tools.
# For example:
#
# "Tell me the leave balance and WFH days."
#
# Gemini may request:
#   1. get_leave_balance
#   2. get_wfh_days
# ---------------------------------------------------------

tool_responses = []

for part in response.candidates[0].content.parts:

    if part.function_call:

        function_name = part.function_call.name
        tool_arguments = part.function_call.args

        print("Gemini requested tool:", function_name)
        print("Tool arguments:", tool_arguments)

        # Find the actual Python function
        # using our tool registry.
        tool_function = TOOLS[function_name]

        # Execute the selected tool with the
        # arguments generated by Gemini.
        tool_result = tool_function(**tool_arguments)

        print("Tool result:", tool_result)

        # Convert the Python result into a format
        # Gemini can understand.
        tool_response = types.Part.from_function_response(
            name=function_name,
            response={
                "result": tool_result
            }
        )

        # Store every tool response.
        tool_responses.append(tool_response)

# ---------------------------------------------------------
# Send all tool results back to Gemini.
#
# Gemini now receives the results from every tool
# it requested and can create the final answer.
# ---------------------------------------------------------

final_response = client.models.generate_content(
    model="gemini-3.5-flash-lite",

    contents=[
        # The original user question.
        types.Content(
            role="user",
            parts=[
                types.Part.from_text(
                    text=user_question
                )
            ]
        ),

        # Gemini's original response containing
        # the function call(s).
        response.candidates[0].content,

        # Results from all executed tools.
        types.Content(
            role="user",
            parts=tool_responses
        )
    ],

    config=types.GenerateContentConfig(
        tools=[tool]
    )
)


# Print the final answer generated by Gemini.
print("\nFinal answer:")
print(final_response.text)