# ---------------------------------------------------------
# Company AI Agent - Tool Executor
#
# This file is responsible for safely executing tools.
#
# Gemini decides which tool it wants to use.
# This layer checks whether that tool is allowed
# and then executes the actual Python function.
# ---------------------------------------------------------

from .tools import TOOLS


def execute_tool(function_name, tool_arguments):
    """
    Safely execute an approved tool.

    Parameters:
        function_name:
            Name of the tool requested by Gemini.

        tool_arguments:
            Arguments generated by Gemini for the tool.

    Returns:
        A dictionary containing either:
        - success=True and the tool result
        - success=False and an error message
    """

    # -----------------------------------------------------
    # Security check
    #
    # Only functions registered inside TOOLS can execute.
    # This prevents the LLM from executing arbitrary code.
    # -----------------------------------------------------

    if function_name not in TOOLS:

        print("Blocked unknown tool:", function_name)

        return {
            "success": False,
            "error": "The requested tool is not available."
        }

    try:

        # -------------------------------------------------
        # Get the approved Python function.
        # -------------------------------------------------

        tool_function = TOOLS[function_name]

        # -------------------------------------------------
        # Execute the function using the arguments
        # generated by Gemini.
        # -------------------------------------------------

        result = tool_function(**tool_arguments)

        print("Tool executed successfully:", function_name)

        return {
            "success": True,
            "result": result
        }

    except Exception as error:

        # -------------------------------------------------
        # Log the technical error for the developer.
        #
        # We don't expose the actual exception to the user
        # because it may contain internal implementation
        # details.
        # -------------------------------------------------

        print("Tool execution error:", error)

        return {
            "success": False,
            "error": "Tool execution failed."
        }