# ---------------------------------------------------------
# Company AI Agent - Embedding
#
# This file converts text into numerical vectors using
# Google's Gemini embedding model.
#
# These vectors are used by our RAG system to find
# semantically similar documents.
# ---------------------------------------------------------

import os

from dotenv import load_dotenv
from google import genai

from .chunker import chunk_text
from .document_loader import load_documents


# Load environment variables from .env.
load_dotenv()


# ---------------------------------------------------------
# Create Gemini client.
#
# GEMINI_API_KEY must be present in the .env file.
# ---------------------------------------------------------

client = genai.Client(
    api_key=os.getenv("GEMINI_API_KEY")
)


def create_embedding(text):
    """
    Convert text into an embedding vector.

    The same embedding model should be used for:
    - document embeddings
    - user-question embeddings

    This allows us to compare them in the same vector space.
    """

    response = client.models.embed_content(
        model="gemini-embedding-2",
        contents=text
    )

    # Return the numerical vector generated by Gemini.
    return response.embeddings[0].values


# ---------------------------------------------------------
# Local testing
# ---------------------------------------------------------

if __name__ == "__main__":

    documents = load_documents()

    for document in documents:

        chunks = chunk_text(
            document["content"]
        )

        for index, chunk in enumerate(chunks):

            embedding = create_embedding(chunk)

            print("=" * 60)
            print(f"Document: {document['filename']}")
            print(f"Chunk: {index + 1}")

            # Display the number of dimensions in the vector.
            print(
                f"Embedding dimensions: {len(embedding)}"
            )

            # Display only a few values so the terminal
            # doesn't get flooded with thousands of numbers.
            print(
                f"First 5 values: {embedding[:5]}"
            )